# Generated by Django 5.1.1 on 2024-09-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="No description available"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(default="https://via.placeholder.com/150"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="title",
            field=models.CharField(default="No Title", max_length=255),
            preserve_default=False,
        ),
    ]
